# Generated by Django 5.0.3 on 2024-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press', models.CharField(default=None, max_length=50)),
                ('date_time', models.DateTimeField()),
                ('employee_number', models.IntegerField(blank=True, null=True)),
                ('pieces_ok', models.IntegerField(blank=True, null=True)),
                ('pieces_scrap', models.IntegerField(blank=True, null=True)),
                ('pieces_rework', models.IntegerField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('work_order', models.CharField(blank=True, max_length=50)),
                ('shift', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
