# Generated by Django 5.0.3 on 2024-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productionpress'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionpress',
            name='molder_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
